// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[search].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/fpwjelf/[id].tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/SearchBar.tsx";

const manifest = {
  routes: {
    "./routes/[search].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/fpwjelf/[id].tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/SearchBar.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
